# Generated by Django 5.0.1 on 2024-01-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_time',
            field=models.IntegerField(default=0, verbose_name='Test vaqti'),
        ),
    ]
