# Generated by Django 5.0.1 on 2024-01-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='mistakes',
            field=models.IntegerField(default=0, verbose_name='Xato javoblar soni'),
        ),
    ]
