# Generated by Django 5.0.1 on 2024-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiztaker_mistakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Yechilgan sana'),
        ),
    ]
